### ISSUE TITLE
일반,기업 회원가입 기능 구현

### ISSUE THREAD

**Issue by EunKyu00** [EunKyu00/FictionPlace#1]
## 작업 내역
- 일반 회원가입과 기업 회원가입 기능 구현
- 회원가입 시 company_user와 site_user 각각의 테이블에 정보 저장
- 회원가입 관련 폼과 뷰 구성

## TODO
- [x] 일반회원 회원가입 기능 구현 (폼, 유효성 검사, 저장 기능)
- [x] 기업회원 회원가입 기능 구현 (폼, 유효성 검사, 저장 기능)
- [x] 디비 정보 저장 확인 (회원가입 후 DB에 정보가 정상적으로 저장되는지 확인)

## 참고 사항
- HTML, CSS는 임시 스타일로 작성되었으며, 추후 디자인 수정 예정
