### ISSUE TITLE
일반,기업 로그인 기능 구현

### ISSUE THREAD

**Issue by EunKyu00** [EunKyu00/FictionPlace#2]
## 작업 내역
- 일반 회원 로그인 기능 구현
    - 일반 아이디 및 비밀번호 로그인 처리
    - 로그인 실패 시 에러 메시지 처리
- 기업 회원 로그인 기능 구현
    - 기업 아이디 및 비밀번호 로그인 처리
    - 로그인 실패 시 에러 메시지 처리
- 로그인 성공 시 상단에 사용자 아이디 표시
## TODO
 - [x] 로그인 작성폼 디자인 및 HTML 작성
 - [x]  일반 로그인 서비스 구현 (아이디, 비밀번호 검증, 세션 처리)
 - [x]  기업 로그인 서비스 구현 (아이디, 비밀번호 검증, 세션 처리)
 - [x] 로그인 성공 후 리디렉션 처리 구현 (메인 페이지로 이동)
 - [x]  로그인 실패 시 에러 메시지 출력 구현

## 참고 사항
- 로그인 성공 시 상단에 표시되는 아이디는 세션을 통해 사용자 정보를 표시함
- HTML과 CSS는 임시로 작성된 스타일임. 추후 디자인 개선 예정
- 추후 카카오 로그인 기능 구현 예정
