### ISSUE TITLE
게시판 기능 구현

### ISSUE THREAD

**Issue by EunKyu00** [EunKyu00/FictionPlace#3]
##TODO
- [x] 로그인한 사용자 게시판 타입 선택 후 게시글 등록
- [x] 본인이 작성 한 게시글 수정,삭제
- [x] 게시글 작성 후 게시글 리스트 리다이렉트 확인
- [x] 게시판 상세보기 페이지 구현
- [x] 게시글 작성 시 유효성 검사 추가 (제목, 내용)
- [x] 게시글, 댓글 작성자 정보 표시
- [x] 게시글 추천, 댓글 개수 표시 기능
- [x] 댓글 등록, 삭제

##참고사항
- 게시글, 댓글  수정,삭제 버튼은 작성자만 보임
- html,css 수정해야함
