### ISSUE TITLE
프로필 기능 구현

### ISSUE THREAD

**Issue by EunKyu00** [EunKyu00/FictionPlace#8]
## TODO
- [x] 일반회원 로그인 시, 프로필 페이지에 일반 회원 본인의 닉네임 및 이메일 정보가 표시되도록 구현.
- [x] 기업회원 로그인 시, 프로필 페이지에 해당 기업의 회사명과 이메일 정보가 표시되도록 기능 구현.
- [x] 닉네임, 이메일, 페스워드 정보수정 기능 구현
